
  SELECT TEST_SCHED_ENTRY.[IDENTITY],   
         TEST_SCHED_ENTRY.ANALYSIS_ID,   
         ltrim(TEST_SCHED_ENTRY.ORDER_NUM),   
         TEST_SCHED_ENTRY.STD_TEST,   
         TEST_SCHED_ENTRY.REPLICATE_COUNT,   
         TEST_SCHED_ENTRY.IS_ANALYSIS,   
         TEST_SCHED_ENTRY.COMPONENT_LIST,   
         TEST_SCHED_HEADER.[IDENTITY],   
         TEST_SCHED_HEADER.[DESCRIPTION],   
         TEST_SCHED_HEADER.MODIFIABLE,   
         TEST_SCHED_HEADER.MODIFIED_ON,   
         TEST_SCHED_HEADER.MODIFIED_BY,   
         TEST_SCHED_HEADER.REMOVEFLAG,   
         TEST_SCHED_HEADER.GROUP_ID   
    FROM TEST_SCHED_ENTRY,   
         TEST_SCHED_HEADER     
    ORDER BY MODIFIED_ON, TEST_SCHED_HEADER.[IDENTITY], 
             TEST_SCHED_ENTRY.ORDER_NUM;