  SELECT JOB_TEMPLATE.[IDENTITY],   
         JOB_TEMPLATE.BROWSE_DESCRIPTION,   
         JOB_TEMPLATE.MODIFIED_ON,   
         JOB_TEMPLATE.MODIFIED_BY,   
         JOB_TEMPLATE.MODIFIABLE,   
         JOB_TEMPLATE.REMOVEFLAG,   
         JOB_TEMPLATE.GROUP_ID,   
         JOB_TEMPLATE.PROMPT_FOR_NAME,   
         JOB_TEMPLATE.SAMPLE_SYNTAX_ID,   
         JOB_TEMPLATE.SAMPLE_TEMPLATE_ID,   
         JOB_TEMPLATE.SAMPLE_REPEAT_COUNT,   
         JOB_TEMPLATE.JOB_SYNTAX_ID,   
         JOB_TEMPLATE.CREATION_TITLE,   
         JOB_TEMPLATE.IS_ENVIRONMENTAL   
    FROM JOB_TEMPLATE
    ORDER BY MODIFIED_ON,[IDENTITY] ;