  SELECT ltrim(TEST.TEST_NUMBER),   
         TEST.ANALYSIS,   
         ltrim(TEST.[SAMPLE]),   
         TEST.PREPARATION,   
         TEST.TEST_COUNT,   
         TEST.[STATUS],   
         TEST.OLD_STATUS,   
         TEST.DATE_STARTED,   
         TEST.STARTER,   
         TEST.DATE_COMPLETED,   
         TEST.COMPLETER,   
         TEST.DATE_AUTHORISED,   
         TEST.AUTHORISER,   
         TEST.COMPONENT_REPLICATES,   
         ltrim(TEST.WORKSHEET),   
         TEST.WORKSHEET_POSITION,   
         TEST.REPLICATE_TEST,   
         TEST.INSTRUMENT,   
         TEST.TEST_PRIORITY,   
         TEST.ON_SPEC,   
         TEST.TEST_SCHEDULE,   
         ltrim(TEST.ORDER_NUM),   
         TEST.HAS_RESULT_LIST,   
         TEST.COMPONENT_LIST,   
         ltrim(TEST.ANALYSIS_VERSION),   
         TEST.PREPARATION_BATCH,   
         TEST.INSTRUMENT_BATCH,   
         TEST.PARENT_TEST,   
         TEST.INSPECTION_HEADER,   
         TEST.TRIGGER_RULE,   
         TEST.TRIGGER_ANALYSIS,   
         TEST.STAT_DOUBLE_ATT_FAIL,   
         TEST.VALIDATION_STATUS,   
         TEST.AUTHORISATION_COMMENT,   
         TEST.AUTO_VALIDATE,   
         TEST.HAS_INCIDENTS
    FROM TEST
ORDER BY TEST.TEST_NUMBER ;