  SELECT MLP_HEADER.[IDENTITY],   
         MLP_HEADER.PRODUCT_CODE,   
         ltrim(MLP_HEADER.ENTRY_CODE),   
         MLP_HEADER.PRODUCT_GROUP,   
         MLP_HEADER.[DESCRIPTION],   
         MLP_HEADER.TEST_SCHEDULE,   
         MLP_HEADER.PRODUCT_STATUS,   
         MLP_HEADER.MODIFIED_ON,   
         MLP_HEADER.MODIFIED_BY,   
         MLP_HEADER.MODIFIABLE,   
         MLP_HEADER.REMOVEFLAG,   
         ltrim(MLP_HEADER.PRODUCT_VERSION),   
         MLP_HEADER.VERSION_COMMENT,   
         MLP_HEADER.VERSION_STATUS,   
         MLP_HEADER.CREATED_DATE         
    FROM MLP_HEADER
ORDER BY MODIFIED_ON,[IDENTITY],PRODUCT_VERSION   ;