  SELECT TEMPLATE_FIELDS.TABLE_NAME,
		 TEMPLATE_FIELDS.TEMPLATE_ID,
		 TEMPLATE_FIELDS.FIELD_NAME,
		 ltrim(TEMPLATE_FIELDS.ORDER_NUMBER),
		 TEMPLATE_FIELDS.DEFAULT_TYPE,
		 TEMPLATE_FIELDS.DEFAULT_VALUE,
		 TEMPLATE_FIELDS.PROMPT_FLAG,
		 TEMPLATE_FIELDS.COPY_FLAG,
		 TEMPLATE_FIELDS.DISPLAY_FLAG,
		 TEMPLATE_FIELDS.MANDATORY_FLAG
    FROM TEMPLATE_FIELDS
ORDER BY TABLE_NAME, TEMPLATE_ID, FIELD_NAME;	