  SELECT MLP_LEVEL.LEVEL_ID,   
         MLP_LEVEL.[DESCRIPTION],   
         MLP_LEVEL.LEVEL_TYPE,   
         MLP_LEVEL.MESSAGE_ACTION,   
         MLP_LEVEL.REPORT_ACTION,   
         MLP_LEVEL.RESULT_ACTION,   
         MLP_LEVEL.DISPLAY_MESSAGE,   
         MLP_LEVEL.REPORT_NAME,   
         MLP_LEVEL.ROUTINE_NAME,   
         MLP_LEVEL.MODIFIED_ON,   
         MLP_LEVEL.MODIFIED_BY,   
         MLP_LEVEL.GROUP_ID,   
         MLP_LEVEL.AQL_LEVEL,   
         MLP_LEVEL.INCIDENT,   
         MLP_LEVEL.INCIDENT_TEMPLATE   
    FROM MLP_LEVEL   
	ORDER BY MODIFIED_ON,LEVEL_ID;